webapp/apps/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from .views import MyLoginView, MySignupView, MyLogoutView, HomePage, UpdateProfileView

app_name = "core"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="core:login", permanent=False), name="index"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("signup/", MySignupView.as_view(), name="signup"),
    path("accounts/logout/", MyLogoutView.as_view(), name="logout"),
    # Password Reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="core/pass/password_reset_form.html",
            email_template_name="core/pass/password_reset_email.html",
            subject_template_name="core/pass/password_reset_subject.txt",
            success_url=reverse_lazy("core:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="core/pass/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/pass/password_reset_confirm.html",
            success_url=reverse_lazy("core:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/pass/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("home/", HomePage.as_view(), name="home"),
    path("update-profile/", UpdateProfileView.as_view(), name="update_profile"),
    # Password change
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="core/pass_2/password_change_form.html",
            success_url=reverse_lazy("core:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="core/pass_2/password_change_done.html"
        ),
        name="password_change_done",
    ),
]

webapp/apps/employee/urls.py
from django.urls import path
from .views import EmployeeListView

app_name = "employee"

urlpatterns = [
    path("list/", EmployeeListView.as_view(), name="employee_list"),
]

webapp/apps/task/urls.py
from django.urls import path
from .views import (
    FileCreateView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TaskUpdateView,
)

app_name = "task"

urlpatterns = [
    path("list/", TaskListView.as_view(), name="task_list"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("file-create/", FileCreateView.as_view(), name="file_create"),
]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("tasks/", include("task.urls", namespace="task")),
    path("employees/", include("employee.urls", namespace="employee")),
]

schema_view = get_schema_view(
    openapi.Info(
        title="EMS API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_urls = [
    path(
        "api/v1/",
        include(
            [
                path("tasks/", include("task.api_urls", namespace="task_apis")),
                path(
                    "employees/",
                    include("employee.api_urls", namespace="employee_apis"),
                ),
            ]
        ),
    ),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

swagger_urls = []

urlpatterns += api_urls
urlpatterns += swagger_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/apps/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class NotDeleted(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_deleted=False)


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True, db_index=True)
    is_deleted = models.BooleanField(default=False, help_text="Used for soft delete")

    all_object = models.Manager()
    objects = NotDeleted()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    class Meta:
        abstract = True


class User(AbstractUser):
    USER_ROLE = (
        ("Manager", "Manager"),
        ("Admin", "Admin"),
        ("Employee", "Employee"),
        ("Other", "Other"),
        ("None", None)
    )

    phone = models.CharField(max_length=32, blank=True, null=True)
    address = models.CharField(max_length=64, blank=True, null=True)
    role = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        choices=USER_ROLE,
        default="Admin",
    )
    dp = models.ImageField(upload_to="dp/", blank=True)

webapp/apps/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField

User = get_user_model()


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_(""),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = [
            "role",
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]
        labels = {
            "role": "",
            "username": "",
            "first_name": "",
            "last_name": "",
            "email": "",
        }
        widgets = {
            "role": forms.Select(attrs={"placeholder": "Select Role"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
            "username": forms.TextInput(attrs={"placeholder": "Username"}),
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs.update({"placeholder": _("Password")})
        self.fields["password2"].widget.attrs.update(
            {"placeholder": _("Confirm password")}
        )


class MyLoginForm(AuthenticationForm):
    username = UsernameField(
        label='',
        widget=forms.TextInput(attrs={"autofocus": True, "placeholder": "Username"})
    )
    password = forms.CharField(
        label=_(""),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "placeholder": "Password"}
        ),
    )

    class Meta:
        labels = {
            "username": "",
        }

webapp/apps/core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, TemplateView, UpdateView

from .forms import MyLoginForm, RegistrationForm

User = get_user_model()

# Create your views here.


class MySignupView(UserPassesTestMixin, SuccessMessageMixin, CreateView):
    form_class = RegistrationForm
    template_name = "core/signup.html/"
    success_url = "/"
    success_message = (
        "%(username)s was created successfully! Now Login with"
        " the same username and password!"
    )

    def test_func(self):
        """
        This is necessary function to use with UserPassesTextMixin
        """
        return self.request.user.is_anonymous

    def handle_no_permission(self):
        """
        This function stop accessing signup page to logged in user
        """
        return HttpResponseRedirect(reverse("users:home"))


class MyLoginView(SuccessMessageMixin, LoginView):
    """
    Here it stops logged in user to access log in page.
    And add success message
    """

    form_class = MyLoginForm
    template_name = "core/login.html"
    redirect_authenticated_user = True
    success_message = "%(username)s, Welcome Here!"


class MyLogoutView(LogoutView):
    http_method_names = ["get", "post", "options"]

    def get(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class HomePage(TemplateView):
    template_name = "core/user/home.html"


@method_decorator(login_required, name="dispatch")
class UpdateProfileView(UpdateView, SuccessMessageMixin):
    model = User
    template_name = "core/user/update_profile.html"
    fields = ["first_name", "last_name", "email", "phone", "address", "dp"]
    success_url = "/home/"
    success_message = "Your Profile Updated Successfully!"

    def get_object(self, **kwargs):
        return self.request.user

webapp/templates/core/user/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">
      <h3 class="d-inline mx-2"><a href="{% url "core:home" %}" style="color: white; text-decoration: none;">EMS</a></h3>
      <h5 class="d-inline mx-5" style="color: white;">{{ user.role }}</h5>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <form class="d-flex mx-auto" method="get" action="{% url 'task:task_list' %}" id="searchForm">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
      <ul class="navbar-nav ml-auto">
        <h6></h6>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% if user.dp %} {{ user.dp.url }}{% else %}{% static 'img/default_dp.png' %}{% endif %}" alt="Profile" width="40" height="40" class="rounded-circle">
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'core:update_profile' %}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'core:password_change' %}">Settings</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<script>
  document.addEventListener('DOMContentLoaded', function() {
      var currentUrl = window.location.href;
      document.getElementById('searchForm').action = currentUrl;
  });
</script>

webapp/templates/core/user/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}
{% block title %}
  Home
{% endblock %}

{% block content %}
  {% include 'core/user/header.html' %}
  {% block home_content %}
    <div class="py-2">
      {% include 'core/user/options.html' %}
    </div>
    {% block content_with_options %}

    {% endblock %}
  {% endblock %}
{% endblock %}

webapp/templates/core/user/options.html
<style>
  /* Custom hover animation */
        .navbar-nav .nav-item:hover .nav-link {
            background-color: #007bff; /* Change background color on hover */
            color: #fff; /* Change text color on hover */
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }
    </style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item  mx-5">
          <a class="nav-link" href="{% url "employee:employee_list" %}">Employees</a>
        </li>
        <li class="nav-item  mx-5">
          <a class="nav-link" href="#">Departments</a>
        </li>
        <li class="nav-item  mx-5">
          <a class="nav-link" href="{% url 'task:task_list' %}">Tasks</a>
        </li>
        <li class="nav-item  mx-5">
          <a class="nav-link" href="#">Salary</a>
        </li>
        <li class="nav-item  mx-5">
          <a class="nav-link" href="#">Mail</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

webapp/templates/core/user/update_profile.html
{% extends 'core/user/home.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
  Update profile
{% endblock %}

{% block home_content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body mx-3">
            <h5 class="card-title text-center"><b>Update Your Profile</b></h5>
            <form class="form-signin" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                <br />
                {{ form|crispy }}
              </fieldset>
              <br />
              <div class="form-group page-button">
                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Update Profile</button>
                <br />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}