webapp/apps/task/urls.py
from django.urls import path
from .views import (
    FileCreateView,
    TaskCreateView,
    TaskDeleteView,
    TaskListView,
    TaskUpdateView,
)

app_name = "task"

urlpatterns = [
    path("list/", TaskListView.as_view(), name="task_list"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("file-create/", FileCreateView.as_view(), name="file_create"),
]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("tasks/", include("task.urls", namespace="task")),
    path("employees/", include("employee.urls", namespace="employee")),
]

schema_view = get_schema_view(
    openapi.Info(
        title="EMS API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_urls = [
    path(
        "api/v1/",
        include(
            [
                path("tasks/", include("task.api_urls", namespace="task_apis")),
                path(
                    "employees/",
                    include("employee.api_urls", namespace="employee_apis"),
                ),
            ]
        ),
    ),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

swagger_urls = []

urlpatterns += api_urls
urlpatterns += swagger_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/apps/task/models.py
import json

from core.models import BaseModel
from core.utils import get_task_upload_name
from django.db import connection, models
from django.utils.translation import gettext_lazy as _
from employee.models import Employee

# Create your models here.


class Task(BaseModel):
    class Status(models.TextChoices):
        TD = "todo", _("To Do")
        IP = "in-progress", _("In Progress")
        IR = "in-review", _("In Review")
        DONE = "done", _("Done")
        OTHER = "other", _("Other")

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    description = models.TextField()
    eta = models.FloatField(
        default=0,
        help_text="Estimated Time of Arrival",
    )
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)

    def __str__(self):
        return f"{self.title} | {self.employee}"

    def to_dict(self, row):
        try:
            return json.loads(row)
        except TypeError:
            return {"detail": "not found"}

    def create_task(self, data):
        result = []
        with connection.cursor() as cursor:
            query = f"""
                    SELECT public.task_task_create(
                            '{data.get('title')}',
                            '{data.get('description')}',
                            {data.get('eta')},
                            '{data.get('start_time')}',
                            '{data.get('end_time')}',
                            {data.get('employee')}
                        )
                    """
            cursor.execute(query)
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def update_task(self, data):
        result = []
        with connection.cursor() as cursor:
            query = f"""
                SELECT public.task_task_update(
                    {data.get("id")},
                    '{data.get("title")}',
                    '{data.get("description")}',
                    {data.get("eta")},
                    '{data.get("start_time")}',
                    '{data.get("end_time")}',
                    {data.get("employee")}
                )
            """
            cursor.execute(query)
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def retrieve_task(self, id):
        result = []
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT public.task_task_retrieve({id})")
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def list_tasks(self, search=""):
        result = []
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT public.task_task_list('{search}')")
            data = cursor.fetchall()
            for row in data:
                result.append(self.to_dict(row[0]))
        return result

    def delete_tasks(self, task_id):
        with connection.cursor() as cursor:
            cursor.execute("SELECT public.task_task_delete(%s)", (task_id,))
            result = cursor.fetchone()
        return result[0]


class Attachment(BaseModel):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    file = models.FileField(_("Task file"), upload_to=get_task_upload_name)

    def __str__(self):
        return f"{self.file}"

    def to_dict(self, row):
        try:
            return json.loads(row)
        except TypeError:
            return {"detail": "not found"}

    def create_task_attachment(self, data):
        result = []
        with connection.cursor() as cursor:
            query = f"""
                SELECT public.task_attachment_create(
                    '{data.get("file")}',
                    {data.get("task_id")}
                )
            """
            cursor.execute(query)
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def update_task_attachment(self, data):
        result = []
        with connection.cursor() as cursor:
            query = f"""
                SELECT public.task_attachment_update(
                    {data.get("id")},
                    '{data.get("file")}',
                    {data.get("task_id")}
                )
            """
            cursor.execute(query)
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def retrieve_task_attachment(self, attachment_id):
        result = []
        with connection.cursor() as cursor:
            query = f"SELECT public.task_attachment_retrieve({attachment_id})"
            cursor.execute(query)
            data = cursor.fetchone()
            result.append(self.to_dict(data[0] if data else None))
        return result[0]

    def list_task_attachments(self):
        """ "Not created stored procedure here. but can be created if needed."""
        pass

    def delete_task_attachments(self, attachment_id):
        with connection.cursor() as cursor:
            cursor.execute("SELECT public.task_attachment_delete(%s)", (attachment_id,))
            result = cursor.fetchone()
        return result[0]

webapp/apps/task/forms.py
from django import forms
from .models import Task, Attachment


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "eta", "start_time", "end_time", "employee"]
        widgets = {
            "start_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }


class FileForm(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ["task", "file"]

webapp/apps/task/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from .models import Attachment, Task

from .forms import FileForm, TaskForm

# Create your views here.


class TaskListView(ListView):
    model = Task
    template_name = "task/list.html"

    def get(self, request, *args, **kwargs):
        obj = self.model()
        search = request.GET.get('search', '')
        context = {"task_list": obj.list_tasks(search)}
        return render(request, "task/list.html", context)


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    template_name = "task/add.html"
    success_url = reverse_lazy("task:task_list")

    def post(self, request, *args, **kwargs):
        obj = self.model()
        _ = obj.create_task(request.POST)
        return redirect(self.success_url)


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task/edit.html"  # Create this template
    success_url = reverse_lazy("task:task_list")

    def put(self, request, *args, **kwargs):
        obj = self.model()
        _ = obj.update_task(request.POST)
        return redirect(self.success_url)


class TaskDeleteView(View):
    model = Task

    def get(self, request, *args, **kwargs):
        obj = self.model()
        task_id = kwargs.get("pk")
        _ = obj.delete_tasks(task_id)
        return redirect("task:task_list")


class TaskRetrieveView(DetailView):
    model = Task
    template_name = "task/edit.html"


class FileCreateView(CreateView):
    model = Attachment
    form_class = FileForm
    template_name = "task/add_file.html"
    success_url = reverse_lazy("task:task_list")

webapp/templates/task/add.html
{% extends 'core/user/home.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
  Add Task
{% endblock %}

{% block content_with_options %}
<style>
  /* Add your custom styles here */
</style>

<div class="container-fluid">
  <div class="block-header">
    <div>
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %} onclick="this.parentElement.style.display='none'">
        {{ message | capfirst }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card mb-3">
        <div class="header text-center mt-4">
          <h4>Add Task</h4>
        </div>

        <div class="card-body">
          <form method="post" id="editTaskForm" action="{% url "task:task_create" %}">
            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-primary">Save Changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/task/add_file.html
{% extends 'core/user/home.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
  Add file
{% endblock %}

{% block content_with_options %}

<div class="container-fluid">
  <div class="block-header">
    <div>
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %} onclick="this.parentElement.style.display='none'">
        {{ message | capfirst }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card mb-3">
        <div class="header text-center mt-4">
          <h4>Edit Task</h4>
        </div>

        <div class="card-body">
          <form method="POST" enctype="multipart/form-data" id="editTaskForm" action="{% url "task:file_create" %}">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Upload file</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/task/edit.html
{% extends 'core/user/home.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
  Edit Task
{% endblock %}

{% block content_with_options %}
<style>
  /* Add your custom styles here */
</style>

<div class="container-fluid">
  <div class="block-header">
    <div>
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %} onclick="this.parentElement.style.display='none'">
        {{ message | capfirst }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card mb-3">
        <div class="header text-center mt-4">
          <h4>Edit Task</h4>
        </div>

        <div class="card-body">
          <form method="post" id="editTaskForm" action="{% url "task:task_edit" task.id %}">
            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-primary">Save Changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/task/list.html
{% extends 'core/user/home.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load debug %}
{% block title %}
  List Tasks
{% endblock %}

{% block content_with_options %}
<style>
  .btn-grad {
    background-image: linear-gradient(to right, #2E8BDC 0%, #005097 100%)
  }

  .btn-grad:hover {
    background-position: right center;
  }
</style>

<div class="container-fluid">
  <div class="block-header">

    <div>
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %} onclick="this.parentElement.style.display='none'">
        {{ message | capfirst }}
      </div>
      {% endfor %}
      {% endif %}
    </div>

  </div>
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">

        <div class="header">
          <div class="row p-4">
            <div class="col-md-4">
              <h4> Manage Task</h4>
            </div>
            <div class="col-md-8">
                <ul class="header-dropdown m-r-5">
                  <a href="{% url "task:task_create" %}" class="btn float-end waves-teal btn-grad" style="color: white;">Add Task</a>
                  <a href="{% url "task:file_create" %}" class="btn btn-outline-primary float-end">Add File</a>
                </ul>
            </div>
          </div>
        </div>

        <div class="card table-responsive mx-4 mb-4">
          <table class="table table-striped datatable-button-html5-basic">
            <thead>
              <tr>
                <th>Sr. No.</th>
                <th>Ttile</th>
                <th>Description</th>
                <th>ETA</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Employee id</th>
                <th>File</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for task in task_list %}
              <tr id="{{ task.id }}">
                <td>{{ forloop.counter }}</td>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.eta }}</td>
                <td>{{ task.start_time }}</td>
                <td>{{ task.end_time }}</td>
                <td>{{ task.employee_id }}</td>
                <td>
                  {% for attachment in task.attachments %}
                  <a href="/media/{{ attachment.file }}" target="_blank">File-{{ forloop.counter }}</a>
                  <br />
                  {% endfor %}
                </td>
                <td>
                    <a href="{% url "task:task_edit" task.id %}" class="btn btn-outline-primary rounded-pill">Edit</a>
                    <form method="get" action="{% url 'task:task_delete' task.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-outline-danger rounded-pill">Delete</button>
                    </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function () {
      // Optional: Close modal when clicking outside of it
      $('#addTaskModal').on('click', function (e) {
        if (e.target === this) {
          $(this).modal('hide');
        }
      });
    });
  </script>
  {% endblock %}