webapp/apps/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from .views import MyLoginView, MySignupView, MyLogoutView, HomePage, UpdateProfileView

app_name = "core"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="core:login", permanent=False), name="index"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("signup/", MySignupView.as_view(), name="signup"),
    path("accounts/logout/", MyLogoutView.as_view(), name="logout"),
    # Password Reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="core/pass/password_reset_form.html",
            email_template_name="core/pass/password_reset_email.html",
            subject_template_name="core/pass/password_reset_subject.txt",
            success_url=reverse_lazy("core:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="core/pass/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/pass/password_reset_confirm.html",
            success_url=reverse_lazy("core:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/pass/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

    path("home/", HomePage.as_view(), name="home"),
    path("update-profile/", UpdateProfileView.as_view(), name="update_profile"),
    # Password change
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="core/pass_2/password_change_form.html",
            success_url=reverse_lazy("core:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="core/pass_2/password_change_done.html"
        ),
        name="password_change_done",
    ),
]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("tasks/", include("task.urls", namespace="task")),
    path("employees/", include("employee.urls", namespace="employee")),
]

schema_view = get_schema_view(
    openapi.Info(
        title="EMS API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_urls = [
    path(
        "api/v1/",
        include(
            [
                path("tasks/", include("task.api_urls", namespace="task_apis")),
                path(
                    "employees/",
                    include("employee.api_urls", namespace="employee_apis"),
                ),
            ]
        ),
    ),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

swagger_urls = []

urlpatterns += api_urls
urlpatterns += swagger_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/apps/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class NotDeleted(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_deleted=False)


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True, db_index=True)
    is_deleted = models.BooleanField(default=False, help_text="Used for soft delete")

    all_object = models.Manager()
    objects = NotDeleted()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    class Meta:
        abstract = True


class User(AbstractUser):
    USER_ROLE = (
        ("Manager", "Manager"),
        ("Admin", "Admin"),
        ("Employee", "Employee"),
        ("Other", "Other"),
        ("None", None)
    )

    phone = models.CharField(max_length=32, blank=True, null=True)
    address = models.CharField(max_length=64, blank=True, null=True)
    role = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        choices=USER_ROLE,
        default="Admin",
    )
    dp = models.ImageField(upload_to="dp/", blank=True)

webapp/apps/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField

User = get_user_model()


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_(""),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_(""),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = [
            "role",
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]
        labels = {
            "role": "",
            "username": "",
            "first_name": "",
            "last_name": "",
            "email": "",
        }
        widgets = {
            "role": forms.Select(attrs={"placeholder": "Select Role"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
            "username": forms.TextInput(attrs={"placeholder": "Username"}),
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs.update({"placeholder": _("Password")})
        self.fields["password2"].widget.attrs.update(
            {"placeholder": _("Confirm password")}
        )


class MyLoginForm(AuthenticationForm):
    username = UsernameField(
        label='',
        widget=forms.TextInput(attrs={"autofocus": True, "placeholder": "Username"})
    )
    password = forms.CharField(
        label=_(""),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "placeholder": "Password"}
        ),
    )

    class Meta:
        labels = {
            "username": "",
        }

webapp/apps/core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, TemplateView, UpdateView

from .forms import MyLoginForm, RegistrationForm

User = get_user_model()

# Create your views here.


class MySignupView(UserPassesTestMixin, SuccessMessageMixin, CreateView):
    form_class = RegistrationForm
    template_name = "core/signup.html/"
    success_url = "/"
    success_message = (
        "%(username)s was created successfully! Now Login with"
        " the same username and password!"
    )

    def test_func(self):
        """
        This is necessary function to use with UserPassesTextMixin
        """
        return self.request.user.is_anonymous

    def handle_no_permission(self):
        """
        This function stop accessing signup page to logged in user
        """
        return HttpResponseRedirect(reverse("users:home"))


class MyLoginView(SuccessMessageMixin, LoginView):
    """
    Here it stops logged in user to access log in page.
    And add success message
    """

    form_class = MyLoginForm
    template_name = "core/login.html"
    redirect_authenticated_user = True
    success_message = "%(username)s, Welcome Here!"


class MyLogoutView(LogoutView):
    http_method_names = ["get", "post", "options"]

    def get(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class HomePage(TemplateView):
    template_name = "core/user/home.html"


@method_decorator(login_required, name="dispatch")
class UpdateProfileView(UpdateView, SuccessMessageMixin):
    model = User
    template_name = "core/user/update_profile.html"
    fields = ["first_name", "last_name", "email", "phone", "address", "dp"]
    success_url = "/home/"
    success_message = "Your Profile Updated Successfully!"

    def get_object(self, **kwargs):
        return self.request.user

webapp/templates/core/pass/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
  Password Reset
{% endblock %}

{% block content %}
  <div class="container my-5">
    <h3 style="color: #607D8B;"><b>Password Reset Complete</b></h3>
    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'core:login' %}">Log in</a>
  </div>
{% endblock %}

webapp/templates/core/pass/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
  Password Reset
{% endblock %}
{% block extra_header %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-8 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body mx-4">
            <h5 class="card-title text-center"><b>Enter New Password</b></h5><br />
            <p>*Please enter your new password twice so we can verify you typed it in correctly.</p>
            <form class="form-signin" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                <br />
                {{ form|crispy }}
              </fieldset>
              <br />
              <div class="d-grid gap-2 col-12 mx-auto">
                <button class="btn btn-lg btn-primary text-uppercase" type="submit">Change My Password</button>
              </div>
              <br /><br />
              <small>
                <p class="text-center">
                  Not registered yet?
                  <a href="{% url 'core:signup' %}"><u><b>Register Now!</b></u></a>
                </p>
              </small>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

webapp/templates/core/pass/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
  Password Reset
{% endblock %}
{% block content %}
<div class="container my-5">
    <h3 style="color: #607D8B;"><b>Password Reset Sent</b></h3>
    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock content %}

webapp/templates/core/pass/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
    <p>Click the following link to reset your password:</p>
    <p><a href="http://{{ domain }}{% url 'core:password_reset_confirm' uidb64=uid token=token %}">Reset Password</a></p>
    <p>If you didn't request a password reset, please ignore this email.</p>
</body>
</html>

webapp/templates/core/pass/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
  Password reset
{% endblock %}
{% block extra_header %}
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock extra_header %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-8 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body mx-4">
            <h5 class="card-title text-center"><b>Password Reset</b></h5><br />
            <p>
              <strong>*Forgotten your password?</strong> Enter your email address below, and we’ll email instructions for setting a new one.
            </p>
            <form class="form-signin" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                <br />
                {{ form|crispy }}
              </fieldset>
              <br />
              <div class="d-grid gap-2 col-12 mx-auto">
                <button class="btn btn-lg btn-primary text-uppercase" type="submit">Reset My Password</button>
              </div>
              <br /><br />
              <small>
                <p class="text-center">
                  Not registered yet?
                  <a href="{% url 'core:signup' %}"><u><b>Register Now!</b></u></a>
                </p>
              </small>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}